### PR TITLE
Remove hawtio-utilities dependency

### PR DESCRIPTION
**Pull request by spadgett**
hawio-utilities was really only used for two small date filters, but brought in some additional 3rd party dependencies like angular-file-upload, which are not needed for the pipeline build.

@gashcrumb Thoughts on this? I'm not sure if defining filters with the same name here will cause a problem if this component is included with hawtio-utilities.

### CODE REVIEW

**Comment by spadgett** [comment]
Please also check my TypeScript :)

**Comment by gashcrumb** [comment]
@spadgett typescript looks good :-)

Lemme check on the filter thing real quick, it may indeed cause issues.  I guess another option would be to work on pulling deps out of hawtio-utilities, could probably move the code that relies on angular-file-upload to another plugin for example.

**Comment by spadgett** [comment]
We could also give the filters unique names.

**Comment by gashcrumb** [comment]
Did a quick test here by grabbing your branch and then installing hawtio-utilities just to check it, I don't see any issues here.

Will have to update the example controller so it uses better values for the duration so those relative timestamps look better though, I'll take care of that a bit later...

**Pull request merged**
